import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange
from .dpt_gs_head import DPTOutputAdapter_fix, PixelwiseTaskWithDPT
from .postprocess import postprocess

class DPTViewHead(PixelwiseTaskWithDPT):
    def __init__(self, mlp_dims, **kwargs):
        """
        mlp_dims: [in_dim, hidden_dim, out_dim]
        """
        self.mlp_dims = mlp_dims
        in_d, hi_d, ou_d = mlp_dims
        
        # Total number of mlp parameters to be generated by DPT
        self.first_layer_size = (in_d * hi_d + hi_d)  # W1, b1
        self.second_layer_size = (hi_d * ou_d + ou_d) # W2, b2
        total_params = self.first_layer_size + self.second_layer_size
        
        # Explicitly set head type to 'view_mlp'
        super().__init__(num_channels=total_params, head_type='view_mlp', **kwargs)

        # Initialize the weights W2 and biases b2 of the final 1×1 convolutional layer to zero.
        last_conv = self.dpt.head[-1]

        if isinstance(last_conv, nn.Conv2d):
            with torch.no_grad():
                # Zero out only the channels for W2 and b2 (starting after first_layer_size).
                start_idx = self.first_layer_size
                last_conv.weight[start_idx:].zero_()
                if last_conv.bias is not None:
                    last_conv.bias[start_idx:].zero_()
            print(f"Zero-initialized W2/b2 channels (from index {start_idx}) in DPTViewHead.")

    def forward(self, x, imgs, img_info):
        # Generate pixelwise MLP parameters via DPT
        # view_mlp_params shape: [B, total_params, H, W]
        view_mlp_params = self.dpt(x, imgs, image_size=(img_info[0], img_info[1]))
        return view_mlp_params

    @staticmethod
    def compute_offset(view_mlp_params, pose_input, mlp_dims):
        """
        A function that computes offsets using the target pose within the decoder.
            view_mlp_params: [B, V_cxt, total_params, H, W]
            pose_input: [B, V_cxt, N, in_dim] (N = H*W) <- relative pose of each context view with regard to one target view
        """
        B, V_cxt, C, H, W = view_mlp_params.shape
        in_d, hi_d, ou_d = mlp_dims

        # Rearrange for computation
        flat_params = rearrange(view_mlp_params, "b v c h w -> (b v h w) c") # [(B * V_cxt * N), C]

        # Compute HyperNetwork
        x_in = rearrange(pose_input, "b v n d -> (b v n) d 1") # [(B * V_cxt * N), in_d, 1]

        idx = 0
        # Layer 1
        w1 = flat_params[:, idx:idx + in_d * hi_d].view(-1, hi_d, in_d)
        idx += in_d * hi_d
        b1 = flat_params[:, idx:idx + hi_d].view(-1, hi_d, 1)
        idx += hi_d
        
        hidden = torch.bmm(w1, x_in) + b1
        hidden = F.relu(hidden)
        
        # Layer 2
        w2 = flat_params[:, idx:idx + hi_d * ou_d].view(-1, ou_d, hi_d)
        idx += hi_d * ou_d
        b2 = flat_params[:, idx:idx + ou_d].view(-1, ou_d, 1)
        
        offset = torch.bmm(w2, hidden) + b2 # [(B*N), ou_d, 1]
        
        # Return Gaussian parameter offsets
        return rearrange(offset.squeeze(-1), "(b v n) d -> b v n d", b=B, v=V_cxt, n=H*W)


def create_view_dpt_head(net, mlp_dims, postprocess_func=postprocess):
    l2 = net.dec_depth
    return DPTViewHead(
        mlp_dims=mlp_dims,
        feature_dim=256,
        last_dim=128,
        hooks_idx=[0, l2*2//4, l2*3//4, l2],
        dim_tokens=[net.enc_embed_dim, net.dec_embed_dim, net.dec_embed_dim, net.dec_embed_dim],
        postprocess=postprocess_func,
        depth_mode=net.depth_mode,
        conf_mode=net.conf_mode
    )