import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange
from typing import List
from .utils import create_uv_grid, position_grid_to_embed
from .dpt_utils import _make_scratch, _make_fusion_block, custom_interpolate


class DPTViewHead(nn.Module):
    def __init__(
        self,
        dim_in: int,
        mlp_dims: List[int], # [in_dim, hidden_dim, out_dim]
        patch_size: int = 14,
        features: int = 256,
        out_channels: List[int] = [256, 512, 1024, 1024],
        intermediate_layer_idx: List[int] = [4, 11, 17, 23],
        pos_embed: bool = True,
        down_ratio: int = 1,
    ) -> None:
        super(DPTViewHead, self).__init__()
        
        self.mlp_dims = mlp_dims
        in_d, hi_d, ou_d = mlp_dims
        
        # Total number of mlp parameters to be generated by DPT
        self.first_layer_size = (in_d * hi_d + hi_d)  # W1, b1
        self.second_layer_size = (hi_d * ou_d + ou_d) # W2, b2
        total_params = self.first_layer_size + self.second_layer_size
        
        self.patch_size = patch_size
        self.pos_embed = pos_embed
        self.down_ratio = down_ratio
        self.intermediate_layer_idx = intermediate_layer_idx

        self.norm = nn.LayerNorm(dim_in)

        # Projection layers (Token -> Feature Map)
        self.projects = nn.ModuleList([
            nn.Conv2d(
                in_channels=dim_in, out_channels=oc,
                kernel_size=1, stride=1, padding=0
            ) for oc in out_channels
        ])

        # Resize layers
        self.resize_layers = nn.ModuleList([
            nn.ConvTranspose2d(out_channels[0], out_channels[0], kernel_size=4, stride=4, padding=0),
            nn.ConvTranspose2d(out_channels[1], out_channels[1], kernel_size=2, stride=2, padding=0),
            nn.Identity(),
            nn.Conv2d(out_channels[3], out_channels[3], kernel_size=3, stride=2, padding=1),
        ])

        # Scratch & Fusion Blocks
        self.scratch = _make_scratch(out_channels, features, expand=False)
        self.scratch.stem_transpose = None
        self.scratch.refinenet1 = _make_fusion_block(features)
        self.scratch.refinenet2 = _make_fusion_block(features)
        self.scratch.refinenet3 = _make_fusion_block(features)
        self.scratch.refinenet4 = _make_fusion_block(features, has_residual=False)

        # Output Heads
        head_features_1 = features
        head_features_2 = 32
        
        self.scratch.output_conv1 = nn.Conv2d(
            head_features_1, head_features_1 // 2, kernel_size=3, stride=1, padding=1
        )
        conv2_in_channels = head_features_1 // 2
        
        # Final output layer: output_dim = total_params
        self.scratch.output_conv2 = nn.Sequential(
            nn.Conv2d(conv2_in_channels, conv2_in_channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.ReLU(inplace=True),
            nn.Conv2d(conv2_in_channels, conv2_in_channels, kernel_size=3, stride=1, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(conv2_in_channels, total_params, kernel_size=1, stride=1, padding=0),
        )

        self.input_merger = nn.Sequential(
            nn.Conv2d(3, 128, 7, 1, 3),
            nn.ReLU(),
        )
        
        # Initialize the weights W2 and biases b2 of the final 1×1 convolutional layer to zero.
        self._init_zero_offset()

    def _init_zero_offset(self):
        last_conv = self.scratch.output_conv2[-1]
        if isinstance(last_conv, nn.Conv2d):
            with torch.no_grad():
                start_idx = self.first_layer_size
                last_conv.weight[start_idx:].zero_()
                if last_conv.bias is not None:
                    last_conv.bias[start_idx:].zero_()
            print(f"[DPTViewHead] Zero-initialized W2/b2 channels (index {start_idx}~) for VGGT backbone.")

    def forward(
        self,
        aggregated_tokens_list: List[torch.Tensor],
        images: torch.Tensor,
        patch_start_idx: int,
        frames_chunk_size: int = 8,
    ) -> torch.Tensor:
        B, S, _, H, W = images.shape
        
        if frames_chunk_size is None or frames_chunk_size >= S:
            return self._forward_impl(aggregated_tokens_list, images, patch_start_idx)

        all_preds = []
        for frames_start_idx in range(0, S, frames_chunk_size):
            frames_end_idx = min(frames_start_idx + frames_chunk_size, S)
            chunk_output = self._forward_impl(
                aggregated_tokens_list, images, patch_start_idx, frames_start_idx, frames_end_idx
            )
            all_preds.append(chunk_output)

        return torch.cat(all_preds, dim=1)

    def _forward_impl(
        self,
        aggregated_tokens_list: List[torch.Tensor],
        images: torch.Tensor,
        patch_start_idx: int,
        frames_start_idx: int = None,
        frames_end_idx: int = None,
    ) -> torch.Tensor:
        
        if frames_start_idx is not None and frames_end_idx is not None:
            images = images[:, frames_start_idx:frames_end_idx].contiguous()

        B, S, _, H, W = images.shape
        patch_h, patch_w = H // self.patch_size, W // self.patch_size

        out = []
        dpt_idx = 0

        for layer_idx in self.intermediate_layer_idx:
            x = aggregated_tokens_list[layer_idx][:, :, patch_start_idx:]
            if frames_start_idx is not None and frames_end_idx is not None:
                x = x[:, frames_start_idx:frames_end_idx]
            
            x = x.contiguous().view(B * S, -1, x.shape[-1])
            x = self.norm(x)
            x = x.permute(0, 2, 1).reshape((x.shape[0], x.shape[-1], patch_h, patch_w))
            
            x = self.projects[dpt_idx](x)
            if self.pos_embed:
                x = self._apply_pos_embed(x, W, H)
            x = self.resize_layers[dpt_idx](x)
            out.append(x)
            dpt_idx += 1

        out = self.scratch_forward(out)
        
        out = custom_interpolate(
            out,
            (int(patch_h * self.patch_size / self.down_ratio), int(patch_w * self.patch_size / self.down_ratio)),
            mode="bilinear", align_corners=True,
        )

        direct_img_feat = self.input_merger(rearrange(images, "b v ... -> (b v) ..."))
        out = out + direct_img_feat

        if self.pos_embed:
            out = self._apply_pos_embed(out, W, H)

        # Pass through final conv layers to get MLP parameters.
        out = self.scratch.output_conv2(out)
        
        # [B*S, C, H, W] -> [B, S, C, H, W]
        out = out.view(B, S, *out.shape[1:])
        
        return out

    def _apply_pos_embed(self, x: torch.Tensor, W: int, H: int, ratio: float = 0.1) -> torch.Tensor:
        patch_w = x.shape[-1]
        patch_h = x.shape[-2]
        pos_embed = create_uv_grid(patch_w, patch_h, aspect_ratio=W / H, dtype=x.dtype, device=x.device)
        pos_embed = position_grid_to_embed(pos_embed, x.shape[1])
        pos_embed = pos_embed * ratio
        pos_embed = pos_embed.permute(2, 0, 1)[None].expand(x.shape[0], -1, -1, -1)
        return x + pos_embed

    def scratch_forward(self, features: List[torch.Tensor]) -> torch.Tensor:
        layer_1, layer_2, layer_3, layer_4 = features
        layer_1_rn = self.scratch.layer1_rn(layer_1)
        layer_2_rn = self.scratch.layer2_rn(layer_2)
        layer_3_rn = self.scratch.layer3_rn(layer_3)
        layer_4_rn = self.scratch.layer4_rn(layer_4)

        out = self.scratch.refinenet4(layer_4_rn, size=layer_3_rn.shape[2:])
        del layer_4_rn, layer_4
        out = self.scratch.refinenet3(out, layer_3_rn, size=layer_2_rn.shape[2:])
        del layer_3_rn, layer_3
        out = self.scratch.refinenet2(out, layer_2_rn, size=layer_1_rn.shape[2:])
        del layer_2_rn, layer_2
        out = self.scratch.refinenet1(out, layer_1_rn)
        del layer_1_rn, layer_1
        out = self.scratch.output_conv1(out)
        return out

    @staticmethod
    def compute_offset(view_mlp_params, pose_input, mlp_dims):
        B, V_cxt, C, H, W = view_mlp_params.shape
        in_d, hi_d, ou_d = mlp_dims

        # Rearrange for computation
        flat_params = rearrange(view_mlp_params, "b v c h w -> (b v h w) c")

        # Compute HyperNetwork
        x_in = rearrange(pose_input, "b v n d -> (b v n) d 1")

        idx = 0
        # Layer 1
        w1 = flat_params[:, idx:idx + in_d * hi_d].view(-1, hi_d, in_d)
        idx += in_d * hi_d
        b1 = flat_params[:, idx:idx + hi_d].view(-1, hi_d, 1)
        idx += hi_d
        
        hidden = torch.bmm(w1, x_in) + b1
        hidden = F.relu(hidden)
        
        # Layer 2
        w2 = flat_params[:, idx:idx + hi_d * ou_d].view(-1, ou_d, hi_d)
        idx += hi_d * ou_d
        b2 = flat_params[:, idx:idx + ou_d].view(-1, ou_d, 1)
        
        offset = torch.bmm(w2, hidden) + b2
        
        # Return Gaussian parameter offsets
        return rearrange(offset.squeeze(-1), "(b v n) d -> b v n d", b=B, v=V_cxt, n=H*W)